spring:
  profiles:
    include: oauth, db

  session:
    store-type: jdbc

  jpa:
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# debug log 에서 parameter 정보 보이도록 활성화.
  http:
    log-request-details: true

logging:
  level:
    org.springframework: info
    org.springframework.web.servlet: debug
  pattern:
    console: "%d{MM-dd HH:mm:ss} [%X{visitorIp}] [%thread] %-5level %logger – %msg%n"


--- #구분
spring:
  profiles: real

  mustache:
    prefix: file:///app/repo/justsite/src/main/resources/templates/
    cache: false

  resources:
    static-locations: file:///app/repo/justsite/src/main/resources/static

server:
  tomcat:
    basedir: .
    accesslog:
      pattern: "%{yyyy-MM-dd HH:mm:ss}t\t%s\t%r\t%{User-Agent}i\t%{Referer}i\t%a\t%b"
      enabled: true

--- #구분
spring:
  profiles: local

  mustache:
    prefix: file:///C:\Users\Administrator\IdeaProjects\justsite\src\main\resources\templates\
    cache: false
    suffix: .mustache

  resources:
    static-locations: file:///C:\Users\Administrator\IdeaProjects\justsite\src\main\resources\static
